pub mod automation;
pub mod editor;
pub mod files;
pub mod ghostty;
pub mod git;
pub mod notifications;
pub mod paths;
pub mod persistence;
pub mod process;
pub mod settings;
pub mod sparkle;
mod terminal_support;
pub mod window;
