pub mod automation;
pub mod commit_message;
pub mod editor;
pub mod files;
pub mod ghostty;
pub mod git;
pub mod library;
mod login_shell;
pub mod notifications;
pub mod paths;
pub mod persistence;
mod process;
pub mod settings;
pub mod sparkle;
pub mod terminal_keyboard;
mod terminal_support;
pub(crate) use terminal_support::publish_terminal_palette;
pub mod usage;
pub mod window;
pub mod work_items;
