pub mod alacritty;
pub mod automation;
pub mod editor;
pub mod files;
#[cfg(feature = "ghostty")]
pub mod ghostty;
pub mod git;
pub mod notifications;
pub mod paths;
pub mod persistence;
pub mod process;
pub mod settings;
pub mod sparkle;
pub mod window;
