[package]
name = "vibra-remote"
version = "0.1.0"
edition = "2024"
[dependencies]
anyhow = "1"
base64 = "0.22"
snow = "=0.10.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "net", "time", "sync", "macros"] }
tokio-tungstenite = { version = "0.28", features = ["rustls-tls-native-roots"] }
futures-util = { version = "0.3", features = ["sink"] }
url = "2"
vibra-remote-protocol = { path = "../protocol" }
